In [ ]:
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
from sklearn.preprocessing import LabelBinarizer # Label encoding, 1-hot encoding, multi-encoding
# LABEL binarizer is a 1-hot encoded MATRIX 
import cv2
import urllib.request
import numpy as np
import random
import os
from keras.preprocessing.image import ImageDataGenerator, img_to_array
from sklearn.model_selection import train_test_split
from keras import backend # backend -> tf/theano etc
from keras.layers.core import Dense, Dropout, Flatten, Activation
from keras.layers.convolutional import Conv2D, MaxPooling2D
from keras.layers.normalization import BatchNormalization
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.optimizers import Adam
from keras.models import Sequential # no parallel, no cycles 
%pylab inline

Populating the interactive namespace from numpy and matplotlib


/usr/local/lib/python3.6/dist-packages/IPython/core/magics/pylab.py:161: UserWarning: pylab import has clobbered these variables: ['random']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [ ]:
def url_to_image(url):
	# download the image, convert it to a NumPy array, and then read
	# it into OpenCV format
	resp = urllib.request.urlopen(url)
	image = np.asarray(bytearray(resp.read()), dtype="uint8")
	image = cv2.imdecode(image, cv2.IMREAD_COLOR)
	# return the image
	return image

In [ ]:
animals = ['cats','dogandrat','dogs','rats','cheetah','cows','deer','ducks','elephants','foxes','giraffes','goats','hens','horses','lions','monkeys','parrots','pigs','sheep','tigers','fish','donkey','rabbit','catsanddogs','catsandrats','tigerandlion','dogandsheep','henandcat','henanddog','horseandcat','horseanddog','monkeyandcat','monkeyanddog','parrotandcat']
numbers = [598,248,594,592,599,599,591,601,597,598,600,595,600,599,599,600,594,601,599,598,599,602,599,236,200,150,147,148,143,149,149,151,149,149]
print(len(animals))
print(len(numbers))

34
34


In [ ]:
containers = ['dogs','cats','rats','cheetah','cows','deer','ducks','elephants','foxes','giraffes','goats','hens','horses','lions','monkeys','parrots','pigs','sheep','tigers','fish','donkey']
print(len(containers))

21


In [ ]:
classes = {'dogs': 0,
'cats':1,
'rats':2,'cheetah' : 3,'cows': 4,'deer' :5 ,'ducks' : 6,'elephants' : 7,'foxes':8,'giraffes':9,'goats':10,'hens':11,'horses':12,'lions':13,'monkeys':14,'parrots':15,'pigs':16,'sheep':17,'tigers':18,'fish':19,'donkey':20, 'rabbit':21}

In [ ]:
# image = url_to_image('https://animalsdataset.blob.core.windows.net/' + animals[6] + '/' + str(299) + '.jpg')
# imgplot = plt.imshow(image)
# plt.show()
name = 'cowanddog'
if 'and' in name:  
        names = name.split('and')
        for i in range(len(names)):
          names[i] = names[i] + 's'
print(classes[names[0]])


4


In [ ]:
import time
data = []
labels = []
for i in range(len(animals)):
  for fname in range((numbers[i])):
    if len(str(fname))==3:
      path = 'https://animalsdataset.blob.core.windows.net/' + animals[i]+ '/' + str(fname) + '.jpg'
      try:
        image = url_to_image(path)
      except:
        continue
    if len(str(fname))==2:
      path = 'https://animalsdataset.blob.core.windows.net/' + animals[i] + '/0' + str(fname) + '.jpg'
      try:
        image = url_to_image(path)
      except:
        continue
    if len(str(fname))==1:
      path = 'https://animalsdataset.blob.core.windows.net/' + animals[i] + '/00' + str(fname) + '.jpg'
      try:
        image = url_to_image(path)
      except:
        continue
    try:
      imgdata = cv2.resize(image,(96,96))
      print("TRY "+ path)  #### path
      data.append(imgdata)
      label = []
      print(i)
      for z in range(len(containers)):
        label.append(0)
      naming = []
      if 'and' in animals[i]:  
        names = animals[i].split('and')
        for w in range(len(names)):
          names[w] = names[w] + 's'
          naming.append(names[w])
      else:
        naming.append(animals[i])
      print(naming)
      for t in range(len(naming)):
        label[classes[naming[t]]]=1  
      label = np.asarray(label)
      print(label)
      labels.append(label)
    except:
      continue
 



TRY https://animalsdataset.blob.core.windows.net/cats/000.jpg
0
['cats']
kuch
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
TRY https://animalsdataset.blob.core.windows.net/cats/001.jpg
0
['cats']
kuch
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
TRY https://animalsdataset.blob.core.windows.net/cats/002.jpg
0
['cats']
kuch
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
TRY https://animalsdataset.blob.core.windows.net/cats/003.jpg
0
['cats']
kuch
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
TRY https://animalsdataset.blob.core.windows.net/cats/004.jpg
0
['cats']
kuch
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
TRY https://animalsdataset.blob.core.windows.net/cats/005.jpg
0
['cats']
kuch
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
TRY https://animalsdataset.blob.core.windows.net/cats/006.jpg
0
['cats']
kuch
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
TRY https://animalsdataset.blob.core.windows.net/cats/007.jpg
0
['cats']
kuch
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
TRY https://animalsdatas

In [ ]:
print(len(labels))
print((len(data)))