<a href="https://colab.research.google.com/github/QwertyApoorv987/Object_Detection/blob/main/Finding_Labels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
################## labels done ################################

labels = []
import os
animals = ['dogs','cats','rats']
classes = {'dogs': 0,
'cats':1,
'rats':2}

path =['dogs','cats','rats','dogsandcats','ratsanddogs']
for impath in path:
  label = [0] * len(animals)
  #label =np.zeros(len(animals))
  #label.astype(int)
  if 'and' in impath:
    names = impath.split('and')
    for i in range(len(names)):
      label[classes[names[i]]]=1   #### adding 1 to names[0] and names[1]
    #label =label.tolist()
    labels.append(label)
  else:
    label[classes[impath]]=1
    #label =label.tolist()
    labels.append(label)
print(labels)

[[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 0], [1, 0, 1]]


In [56]:
print(labels)

[array([1., 0., 0.]), array([0., 1., 0.]), array([0., 0., 1.]), array([1., 1., 0.]), array([1., 0., 1.])]


In [47]:
l = np.zeros([3])
l[2] = 1
la = []
la.append(l)
print(la)

[array([0., 0., 1.])]


In [28]:
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer
labels = np.array(labels)
lb = MultiLabelBinarizer()
print(lb.fit_transform(labels))


print(labels)

[[0 0 0 1 0 1 1 0 0 1 0]
 [1 1 0 0 0 0 0 0 0 1 1]
 [1 0 0 0 0 0 0 1 0 1 1]
 [0 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 1 0 0]]
['dogs' 'cats' 'rats' list(['dogs', 'cats']) list(['rats', 'dogs'])]
