<a href="https://colab.research.google.com/github/QwertyApoorv987/Object_Detection/blob/main/Loading_images_from_azure_containers_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
from sklearn.preprocessing import LabelBinarizer # Label encoding, 1-hot encoding, multi-encoding
# LABEL binarizer is a 1-hot encoded MATRIX 
import cv2
import urllib.request
import numpy as np
import random
from keras.preprocessing.image import ImageDataGenerator, img_to_array
from sklearn.model_selection import train_test_split
from keras import backend # backend -> tf/theano etc
from keras.layers.core import Dense, Dropout, Flatten, Activation
from keras.layers.convolutional import Conv2D, MaxPooling2D
from keras.layers.normalization import BatchNormalization

from keras.models import Sequential # no parallel, no cycles 

In [41]:
def url_to_image(url):
	# download the image, convert it to a NumPy array, and then read
	# it into OpenCV format
	resp = urllib.request.urlopen(url)
	image = np.asarray(bytearray(resp.read()), dtype="uint8")
	image = cv2.imdecode(image, cv2.IMREAD_COLOR)
	# return the image
	return image

In [42]:
#image = url_to_image('https://rawimagestraining.blob.core.windows.net/cheetah/000.png')
#print(img)

[[[ 58 122 110]
  [ 43 107  95]
  [  6  70  58]
  ...
  [ 25  93  92]
  [ 29  97  96]
  [ 29  97  96]]

 [[ 51 115 103]
  [ 57 121 109]
  [ 12  76  64]
  ...
  [ 27  95  94]
  [ 28  96  95]
  [ 28  96  95]]

 [[ 31  96  81]
  [ 43 108  93]
  [  7  72  57]
  ...
  [ 24  90  89]
  [ 23  89  88]
  [ 23  89  88]]

 ...

 [[ 17  68  30]
  [ 17  69  32]
  [ 21  72  38]
  ...
  [ 45  99  82]
  [ 48 102  85]
  [ 48 102  85]]

 [[ 45  94  56]
  [  9  60  23]
  [ 18  67  35]
  ...
  [ 50 100  82]
  [ 48  96  78]
  [ 56 104  86]]

 [[ 45  94  56]
  [ 11  59  23]
  [ 18  67  35]
  ...
  [ 52 100  82]
  [ 51  95  78]
  [ 59 103  86]]]


In [63]:
animals = ['cheetah', 'monkeys', 'elephants']
len(animals)

3

In [66]:
 path = 'https://rawimagestraining.blob.core.windows.net/' + animals[2]+ '/' + str(fname) + '.png'
path = 'https://rawimagestraining.blob.core.windows.net/' + animals[i] + '/' + '0' + str(fname) + '.png'
print(path)

https://rawimagestraining.blob.core.windows.net/monkeys/0101.png


In [67]:
fname = 0
data = []
i = 0
for i in range(len(animals)):
  fname = 0
  for fname in range(150):
    if len(str(fname))==3:
      path = 'https://rawimagestraining.blob.core.windows.net/' + animals[i]+ '/' + str(fname) + '.png'
      fname = fname + 1
      image = url_to_image(path)
    if len(str(fname))==2:
      path = 'https://rawimagestraining.blob.core.windows.net/' + animals[i] + '/0' + str(fname) + '.png'
      fname = fname + 1
      image = url_to_image(path)
    if len(str(fname))==1:
      path = 'https://rawimagestraining.blob.core.windows.net/' + animals[i] + '/00' + str(fname) + '.png'
      fname = fname + 1
      image = url_to_image(path)
    imgdata = cv2.resize(image,(96,96)) 
    data.append(imgdata)

In [68]:
len(data)

450

In [27]:
data = []
labels = [] 
# read all images
all_images = sorted(list(paths.list_images(HP_dataset))) ### listing all the images that have Data in their path
all_images[:5]

['Data/Cheetah/000.png',
 'Data/Cheetah/001.png',
 'Data/Cheetah/002.png',
 'Data/Cheetah/003.png',
 'Data/Cheetah/004.png']

In [32]:
data = []
coordinates = []
import os
for impath in all_images:
  img = cv2.imread(impath)
  resized = cv2.resize(img, (96,96) ) ### every image to (96,96) aspect ratio
  imageData = img_to_array(resized)
  img2 = imageData[0:95,0:95]
  indices = np.where(img2!= [0])
  coordinates.append((indices[0], indices[1]))
  data.append(imageData)

In [33]:
coordinates[0]

(array([ 0,  0,  0, ..., 94, 94, 94]), array([ 0,  0,  0, ..., 94, 94, 94]))